/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DInput: typeof import('./src/components/DynamicForm/components/DInput.vue')['default']
    DTimePick: typeof import('./src/components/DynamicForm/components/DTimePick.vue')['default']
    DTimePicker: typeof import('./src/components/DynamicForm/components/DTimePicker.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
